title               : Dushyant Trivedi
description         : >-
                     ""
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
remote_theme        : trivedidushyant/portfolYOU       # theme 

### Plugins ###

plugins:
  - jemoji
  - jekyll-sitemap


### Navbar Settings ###
nav_exclude:                                            # The following path is excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md 
  - pages/projects.html
  - pages/github.md

### Author Info ###
author:
  name              : Dushyant Trivedi
  image             : https://raw.githubusercontent.com/trivedidushyant/trivedidushyant.github.io/master/_images/dp.jpeg
  github            : trivedidushyant

### Disqus
disqus: portfolio-bnhbmol6a5


### Posts ###
permalink: /blog/:title

markdown: kramdown
kramdown:
   math_engine: mathjax

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "posts"                                  
    values:
      comments: true
      
### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"

gems:
  - jekyll-sitemap  

